<!DOCTYPE html>
<html>
<form target="_self" method="post">
<?php
    if($action ==='signup'):
?>

<div class="container">
        <label for="name"><b>Name</b></label>
        <input type="text" name="user[name]" required
            class="form-control"<?php echo error_field('name', $errors); ?>/>
    </div>

    <div class="container">   
        <label for="email"><b>email</b></label>
        <input type="text" name="user[email]" required
            class="form-control"<?php echo error_field('email', $errors); ?>/>
    </div>

    <div class="container">   
        <label for="ID"><b>ID</b></label>
        <input type="text" name="user[ID]" required
            class="form-control"<?php echo error_field('ID', $errors); ?>/>
    </div>

    <div class="container">   
        <label for="password"><b>Password</b></label>
        <input type="text" name="user[password]" required 
            class="form-control"<?php echo error_field('password', $errors); ?>/>
       
        <input type="text"  name="user[passwordRepeat]" required 
            class="form-control"<?php echo error_field('password', $errors); ?>/>
    </div>
    <?php
    endif
    <?


</html>