<!DOCTYPE html>
<html>
<style>

input[type=text], input[type=password] {
  width: auto;
  padding: 10px 15px;
  margin: 8px 5px;
  border: 1px solid #ccc;
  border-radius: 5px;
  color: blue;}

  button {
  color: white;
  padding: 14px 20px;
  border: none;
  cursor: wait;
  width: auto;}

  button:hover {opacity: 1.0;}
 
  .cancelbtn {
  width: auto;
  padding: 10px 10px;}



</style>

<head>
  <!--Setting the page to phone scale and zoom at 100% -->  
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
 <title> Signup Page</title>
</head>
 <body>
  

             

   
 <?php

 require $template;
 # this is the homepage default page
 #we don't code here for now it'll display all pages
 ?>

</body>
</html>