<!DOCTYPE html>
<html>
<head>
    <title> Welcome Page</title>
</head>
<body>
    <h2>Home page </h2>
    <form action="view" method="post">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" required><br>

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br>

        <label for="Identity Number">ID:</label>
        <input type="ID" id="ID" name="ID" required><br>

        <label for="Cell Number">CellNumber:</label> 
       <input type="CellNumber" id="CellNumber" name="CellNumber" required><br>
    

        <input type="submit" value="Submit">
    </form>
</body>
</html>
