<div class="col-md-8"> <!-- screen width => 768px-->
<h1 class="text-center"> Home Page </h1> <!--Writing to the middle-->
<p class="text-right"><?php  echo $formatted = date("D d/m/Y H:i:s") ?></p> <!--adding date to front page-->
<?php

/*$date = new DateTime();

 echo "Welcome user Please click next to continue \r";
 
 echo '<a href = "localhost/learnerhub/user">
   Next
  </a>';*/


  
?>
</div>