<!DOCTYPE html>
<html>
<head>
    <title> Welcome Page</title>
</head>
<body>
    <h2>Home page </h2>
    <form action="user" method="post">
        <!--This is a page-->
        <!-- This is what we want the user to see (view) -->
        <!-- input only-->
        
        <label for="name">Name:</label>
        <input type="text" name="name" placeholder = "Enter your name" required><br>

        <label for="email">Email:</label>
        <input type="email" name="email" placeholder = "Enter your email" required><br>

        <label for="Identity Number">ID:</label>
        <input type="ID" name="ID" placeholder = "Your 13 digit Identity Number" required><br>

        <label for="Cell Number">CellNumber:</label> 
       <input type="CellNumber" name="CellNumber" placeholder = "Your 10 digit number " required><br>
    

        <button type = "Continue">Submit</button>
    </form>
</body>
</html>

<?php
// fetching from class into outputting
if($_SERVER['REQUEST_METHOD'] === 'POST')
{ 
    echo"Name: ".$user->get_name();
    echo"<br>";
    echo"email: ".$user->get_email();
    echo"<br>";
    echo"Email: ".$user->get_ID();
    echo"<br>";
    echo"Cellphone: ".$user->get_CellNumber();
    echo"<br>";

}